import assert from "node:assert/strict";
import test from "node:test";

import {
  renderSdkSchemaTypes,
  schemaToType,
} from "../generate-sdk-types.mjs";

test("schemaToType renders references, nullable unions, arrays, and maps", () => {
  assert.equal(
    schemaToType({
      type: "object",
      properties: {
        state: { $ref: "#/components/schemas/State" },
        note: { anyOf: [{ type: "string" }, { type: "null" }] },
        values: { type: "array", items: { type: "integer" } },
        labels: { type: "object", additionalProperties: { type: "string" } },
      },
      required: ["state", "values"],
      additionalProperties: false,
    }),
    `{
  "state": OpenApiSchemas["State"];
  "note"?: string | null;
  "values": Array<number>;
  "labels"?: Record<string, string>;
}`,
  );
});

test("renderSdkSchemaTypes emits a deterministic named schema map", () => {
  const output = renderSdkSchemaTypes({
    components: {
      schemas: {
        State: { type: "string", enum: ["ready", "done"] },
        Payload: {
          type: "object",
          properties: { ok: { type: "boolean" } },
          required: ["ok"],
          additionalProperties: false,
        },
      },
    },
  });

  assert.match(output, /This file is generated by scripts\/generate-sdk-types\.mjs/);
  assert.match(output, /export interface OpenApiSchemas \{/);
  assert.match(output, /"Payload": \{\n    "ok": boolean;\n  \};/);
  assert.match(output, /"State": "ready" \| "done";/);
  assert.match(output, /export type OpenApiSchema<Name extends OpenApiSchemaName>/);
});

test("schemaToType rejects references outside component schemas", () => {
  assert.throws(
    () => schemaToType({ $ref: "#/paths/~1health/get" }),
    /unsupported schema reference/,
  );
  assert.throws(
    () => schemaToType({ not: { type: "string" } }),
    /unsupported schema keywords: not/,
  );
});
