const string = (extra = {}) => ({ type: "string", ...extra });
const integer = (extra = {}) => ({ type: "integer", ...extra });
const number = (extra = {}) => ({ type: "number", ...extra });
const boolean = { type: "boolean" };
const unknown = {};
const timestamp = string({ format: "date-time" });
const nullable = (schema) => ({ anyOf: [schema, { type: "null" }] });
export const ref = (name) => ({ $ref: `#/components/schemas/${name}` });
export const array = (items) => ({ type: "array", items });
const object = (properties, required = Object.keys(properties), extra = {}) => ({
  type: "object",
  properties,
  ...(required.length > 0 ? { required } : {}),
  additionalProperties: false,
  ...extra,
});
const enumString = (...values) => string({ enum: values });

const messageProperties = { ok: boolean, message: string() };
const moduleInfo = object(
  {
    name: string(),
    status: enumString("stopped", "running"),
    version: string(),
    description: string(),
    capabilities: array(string()),
  },
  ["name", "status"],
);
const compilerMetrics = object({
  total_requests: integer({ minimum: 0 }),
  cache_hits: integer({ minimum: 0 }),
  cache_misses: integer({ minimum: 0 }),
  errors: integer({ minimum: 0 }),
  rejected: integer({ minimum: 0 }),
  in_flight: integer({ minimum: 0 }),
  in_flight_peak: integer({ minimum: 0 }),
  avg_duration_ms: number({ minimum: 0 }),
});
const runnerAgentIsolation = enumString(
  "shared_kernel", "container", "virtual_machine", "dedicated_host",
);
const runnerAgentState = enumString("healthy", "degraded", "draining", "offline");
const runnerJobState = enumString(
  "queued", "claimed", "cancel_requested", "succeeded", "failed", "cancelled", "expired",
);
const runnerAgentProperties = {
  agent_id: string(),
  protocol_version: integer({ minimum: 1 }),
  agent_version: string(),
  isolation: runnerAgentIsolation,
  state: runnerAgentState,
  max_concurrent: integer({ minimum: 1 }),
  active_jobs: integer({ minimum: 0 }),
  available_slots: integer({ minimum: 0 }),
  capabilities: array(string()),
  labels: { type: "object", additionalProperties: { type: "string" } },
  kernel_release: nullable(string()),
  message: nullable(string()),
  registered_at: timestamp,
  last_seen_at: timestamp,
  expires_at: timestamp,
};
const runnerJobProperties = {
  job_id: string(),
  kind: string(),
  state: runnerJobState,
  target_agent_id: nullable(string()),
  assigned_agent_id: nullable(string()),
  owner_username: nullable(string()),
  message: string(),
  source_bytes: nullable(integer({ minimum: 0 })),
  program_name: nullable(string()),
  timeout_seconds: integer({ minimum: 1 }),
  result_message: nullable(string()),
  output: nullable(string()),
  created_at: timestamp,
  claimed_at: nullable(timestamp),
  deadline: nullable(timestamp),
  completed_at: nullable(timestamp),
};

export const schemas = {
  ApiMessage: object(messageProperties),
  SystemInfo: object({ name: string(), status: string() }),
  HealthResponse: object({ status: string() }),
  AuthRole: enumString("admin", "teacher", "student"),
  LoginRequest: object({ username: string(), password: string(), otp: string() }),
  LoginResponse: object({
    ...messageProperties,
    username: nullable(string()),
    role: nullable(ref("AuthRole")),
    expires_at: nullable(timestamp),
  }),
  SessionResponse: object({
    authenticated: boolean,
    username: nullable(string()),
    role: nullable(ref("AuthRole")),
    expires_at: nullable(timestamp),
  }),
  TotpBootstrapRequest: object({ username: string(), password: string() }),
  TotpBootstrapResponse: object({
    ...messageProperties,
    issuer: nullable(string()),
    account_name: nullable(string()),
    secret: nullable(string()),
    otpauth_uri: nullable(string()),
  }),
  RegisterRequest: object({ username: string(), password: string() }),
  ChangePasswordRequest: object({
    current_password: string(),
    new_password: string({ minLength: 8 }),
    otp: string(),
  }),
  DeleteAccountRequest: object({ password: string(), otp: string() }),
  ModuleInfo: moduleInfo,
  ModuleControlRequest: object({ name: string({ minLength: 1, maxLength: 128 }) }),
  HeaderModuleItem: object({
    id: string(),
    name: string(),
    description: string(),
    source_url: string({ format: "uri" }),
    downloaded: boolean,
    selected: boolean,
    local_path: string(),
  }),
  SelectedHeaderMetadata: object({
    id: string(),
    include_hint: string(),
    local_path: string(),
    downloaded: boolean,
  }),
  DownloadHeaderRequest: object({ id: string() }),
  SelectHeaderRequest: object({ id: string(), selected: boolean }),
  CommandRequest: object(
    {
      commandType: enumString("ListModules", "StartModule", "StopModule", "RunExperiment"),
      moduleName: string({ minLength: 1, maxLength: 128 }),
    },
    ["commandType"],
  ),
  CommandResponse: object(
    {
      ...messageProperties,
      commandType: enumString("ListModules", "StartModule", "StopModule", "RunExperiment"),
      modules: array(ref("ModuleInfo")),
      module: ref("ModuleInfo"),
      nextPath: string(),
    },
    ["ok", "message", "commandType"],
  ),
  EventRecord: object({
    username: string(),
    timestamp,
    source: string(),
    event_type: string(),
    category: enumString("kernel", "platform"),
    severity: enumString("success", "warning", "error"),
    color: enumString("green", "yellow", "red"),
    payload: unknown,
  }),
  EventSettings: object({
    max_records: integer({ minimum: 1 }),
    overflow_policy: enumString("drop_oldest", "drop_new"),
  }),
  UpdateEventSettingsResponse: object(
    { ...messageProperties, settings: nullable(ref("EventSettings")) },
  ),
  CompilerSettings: object({ resident: boolean, strategy: string() }),
  UpdateCompilerSettingsRequest: object({ resident: boolean }),
  UpdateCompilerSettingsResponse: object({
    ...messageProperties,
    settings: ref("CompilerSettings"),
  }),
  CompilerOperationMetrics: compilerMetrics,
  PerformanceMetrics: object({
    check: ref("CompilerOperationMetrics"),
    completion: ref("CompilerOperationMetrics"),
  }),
  UserScript: object({
    id: string(),
    username: string(),
    title: string(),
    script: string(),
    created_at: timestamp,
    updated_at: timestamp,
  }),
  SaveScriptRequest: object({ title: string(), script: string() }),
  SaveScriptResponse: object(
    { ...messageProperties, record: nullable(ref("UserScript")) },
  ),
  DeleteScriptRequest: object({ id: string() }),
  LabDefinition: object({
    id: string(),
    position: integer({ minimum: 1 }),
    title: string(),
    summary: string(),
    doc_slug: string(),
    template_id: nullable(string()),
  }),
  LabAttempt: object({
    id: string(),
    username: string(),
    lab_id: string(),
    template_id: nullable(string()),
    source: string(),
    source_sha256: string(),
    run_success: boolean,
    stage: string(),
    attach_expected: boolean,
    attach_verified: boolean,
    completed: boolean,
    feedback: array(string()),
    created_at: timestamp,
  }),
  LabProgress: object({
    lab: ref("LabDefinition"),
    status: enumString("not_started", "in_progress", "completed"),
    attempts: integer({ minimum: 0 }),
    latest_stage: nullable(string()),
    latest_feedback: array(string()),
    last_attempt_at: nullable(timestamp),
    completed_at: nullable(timestamp),
  }),
  StudentLearningOverview: object({
    username: string(),
    completed_labs: integer({ minimum: 0 }),
    total_labs: integer({ minimum: 0 }),
    total_attempts: integer({ minimum: 0 }),
    last_activity_at: nullable(timestamp),
    labs: array(ref("LabProgress")),
  }),
  TeacherLearningOverview: object({
    generated_at: timestamp,
    total_labs: integer({ minimum: 0 }),
    active_students: integer({ minimum: 0 }),
    students: array(ref("StudentLearningOverview")),
  }),
  TeacherStudentAttempts: object({
    username: string(),
    attempts: array(ref("LabAttempt")),
  }),
  EbpfCodeRequest: object({ code: string({ minLength: 1, maxLength: 262144 }) }),
  EbpfDiagnostic: object({
    line: integer({ minimum: 1 }),
    column: integer({ minimum: 1 }),
    end_column: integer({ minimum: 1 }),
    severity: string(),
    message: string(),
  }),
  EbpfCheckResponse: object({
    ...messageProperties,
    diagnostics: array(ref("EbpfDiagnostic")),
    stdout: string(),
    stderr: string(),
  }),
  EbpfCompletionRequest: object({
    code: string(),
    line: integer({ minimum: 1 }),
    column: integer({ minimum: 1 }),
  }),
  EbpfCompletionResponse: object({
    ...messageProperties,
    items: array(object({
      label: string(),
      insert_text: string(),
      detail: string(),
      kind: string(),
    })),
  }),
  EbpfRunRequest: object(
    {
      code: string({ minLength: 1, maxLength: 262144 }),
      template_id: string(),
      lab_id: string(),
      program_name: string(),
      runtime_backend: enumString("bpftool", "aya"),
      sampling_per_sec: integer({ minimum: 1 }),
      stream_seconds: integer({ minimum: 0 }),
      enable_kernel_stream: boolean,
      debug_breakpoints: array(integer({ minimum: 1 })),
    },
    ["code"],
  ),
  EbpfRunResponse: object(
    {
      success: boolean,
      stage: string(),
      message: string(),
      compile_stdout: string(),
      compile_stderr: string(),
      load_stdout: string(),
      load_stderr: string(),
      pin_path: nullable(string()),
      debug: ref("EbpfDebugInfo"),
    },
    [
      "success", "stage", "message", "compile_stdout", "compile_stderr",
      "load_stdout", "load_stderr", "pin_path",
    ],
  ),
  EbpfDebugRejectedBreakpoint: object({ line: integer({ minimum: 1 }), reason: string() }),
  EbpfDebugInfo: object({
    mode: string(),
    session_id: nullable(string()),
    requested_lines: array(integer({ minimum: 1 })),
    instrumented_lines: array(integer({ minimum: 1 })),
    rejected: array(ref("EbpfDebugRejectedBreakpoint")),
  }),
  EbpfTemplate: object(
    {
      id: string(),
      name: string(),
      description: string(),
      capability: string(),
      category: string(),
      code: string(),
    },
    ["id", "name", "description", "capability", "code"],
  ),
  EbpfDetachRequest: object({ pin_path: nullable(string()) }, []),
  EbpfDetachResponse: object({
    ...messageProperties,
    detached: array(string()),
    clean: boolean,
    safety_notes: array(string()),
  }),
  EbpfAttachment: object({ pin_path: string(), source: string(), program_name: string() }),
  EbpfRemoteCheckSubmitRequest: object(
    { code: string(), agent_id: string(), program_name: string() },
    ["code", "agent_id"],
  ),
  EbpfRemoteCheckCancelRequest: object({ job_id: string() }),
  EbpfRemoteCheckResponse: object({
    job_id: string(),
    state: runnerJobState,
    agent_id: nullable(string()),
    message: string(),
    result: nullable(ref("EbpfCheckResponse")),
  }),
  EbpfCheckBackendInventory: object({
    local_available: boolean,
    agents: array(object({
      agent_id: string(),
      isolation: runnerAgentIsolation,
      state: runnerAgentState,
      available_slots: integer({ minimum: 0 }),
      max_concurrent: integer({ minimum: 1 }),
    })),
  }),
  RunnerStatus: object({
    mode: string(),
    isolation: string(),
    instance_id: string(),
    max_concurrent: integer({ minimum: 1 }),
    max_per_user: integer({ minimum: 1 }),
    active_total: integer({ minimum: 0 }),
    active_for_current_user: integer({ minimum: 0 }),
    available_slots: integer({ minimum: 0 }),
    execution_timeout_seconds: integer({ minimum: 1 }),
  }),
  RunnerLease: object({
    runner_id: string(),
    username: string(),
    runtime_backend: string(),
    started_at: timestamp,
    deadline: timestamp,
  }),
  RunnerOverview: object({ status: ref("RunnerStatus"), active_leases: array(ref("RunnerLease")) }),
  RunnerAgentRegisterRequest: object(
    {
      agent_id: string(),
      protocol_version: integer({ minimum: 1 }),
      agent_version: string(),
      isolation: runnerAgentIsolation,
      max_concurrent: integer({ minimum: 1 }),
      capabilities: array(string()),
      labels: { type: "object", additionalProperties: { type: "string" } },
    },
    ["agent_id", "protocol_version", "agent_version", "isolation", "max_concurrent"],
  ),
  RunnerAgentHeartbeatRequest: object(
    {
      agent_id: string(),
      state: runnerAgentState,
      active_jobs: integer({ minimum: 0 }),
      available_slots: integer({ minimum: 0 }),
      kernel_release: nullable(string()),
      message: nullable(string()),
    },
    ["agent_id", "state", "active_jobs", "available_slots"],
  ),
  RunnerAgent: object(runnerAgentProperties),
  RunnerAgentRegistrationResponse: object({
    ...runnerAgentProperties,
    credential: string(),
    signature_scheme: string(),
  }),
  RunnerAgentInventory: object({
    generated_at: timestamp,
    enabled: boolean,
    total_agents: integer({ minimum: 0 }),
    online_agents: integer({ minimum: 0 }),
    agents: array(ref("RunnerAgent")),
  }),
  RunnerProbeRequest: object(
    { agent_id: string(), message: string(), timeout_seconds: integer({ minimum: 1 }) },
    ["message"],
  ),
  RunnerCompileCheckRequest: object(
    {
      agent_id: string(),
      source: string(),
      program_name: string(),
      timeout_seconds: integer({ minimum: 1 }),
    },
    ["source"],
  ),
  RunnerJobCancelRequest: object({ job_id: string() }),
  RunnerJobView: object(runnerJobProperties),
  RunnerJobInventory: object({
    generated_at: timestamp,
    total_jobs: integer({ minimum: 0 }),
    jobs: array(ref("RunnerJobView")),
  }),
  RunnerJobClaimRequest: object({ agent_id: string() }),
  RunnerJobLeaseReference: object({ job_id: string(), lease_token: string() }),
  RunnerJobSyncRequest: object(
    { agent_id: string(), leases: array(ref("RunnerJobLeaseReference")) },
    ["agent_id"],
  ),
  RunnerJobResultRequest: object(
    {
      agent_id: string(),
      job_id: string(),
      lease_token: string(),
      state: enumString("succeeded", "failed", "cancelled"),
      message: nullable(string()),
      output: nullable(string()),
    },
    ["agent_id", "job_id", "lease_token", "state"],
  ),
  RunnerJobClaim: object({
    job_id: string(),
    kind: string(),
    message: string(),
    source: nullable(string()),
    program_name: nullable(string()),
    lease_token: string(),
    claimed_at: timestamp,
    deadline: timestamp,
  }),
  RunnerJobClaimResponse: object({ job: nullable(ref("RunnerJobClaim")) }),
  RunnerJobSyncResponse: object({
    cancel_job_ids: array(string()),
    lost_job_ids: array(string()),
  }),
  EnvironmentReport: object({
    overall_ok: boolean,
    generated_at: timestamp,
    runtime_mode: enumString("native-linux", "wsl2", "docker"),
    runtime_guidance: string(),
    checks: array(object({ name: string(), ok: boolean, detail: string() })),
  }),
};
